In [1]:
5,7

(5, 7)

In [2]:
(5,)

(5,)

In [3]:
list_a = [1,3,5,7,9]
list_b = [3,5,6,7,9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [4]:
import numpy as np 
array_a = np.array([1,3,5,7,9])
array_b = np.array([3,5,6,7,9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [7]:
import numpy as np

l = [[1,2,3],[4,5,6]]
array = np.array(1)
array.ndim, array.shape, array.size, array.dtype

(0, (), 1, dtype('int64'))

In [5]:
import numpy as np
np.random.randn(10,5)

array([[ 0.84441504, -1.22901194, -0.28865951,  0.0448865 ,  0.24206287],
       [-0.18614526, -0.75628583,  0.06843717, -0.13595803,  1.22226252],
       [-0.86034621,  0.14022993,  0.01550267, -1.01638058,  0.58925806],
       [ 1.84265075,  0.64058194,  0.1496945 ,  1.12172819, -0.98386321],
       [-0.01202819,  1.53204259, -0.66589598, -0.30513128,  0.57658379],
       [ 1.40350355, -0.24309986,  1.36985114,  1.03076791,  1.86919924],
       [-0.42543667,  2.25343967, -0.49676543,  1.5016558 , -0.23753185],
       [-0.22020916, -1.02840562, -0.86001345, -0.07368052,  0.08071872],
       [ 1.08949109, -1.60386451, -0.00419448,  0.83800591, -0.9220569 ],
       [ 0.54723679,  0.4735684 ,  0.69097695, -0.08029041,  0.11850778]])

In [6]:
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 78,  92,  97,  96,  56],
       [ 78,  73,  91,  80,  59],
       [ 89,  58,  70,  62,  77],
       [ 50,  83, 100,  82,  96],
       [ 54,  71,  75,  59,  79],
       [ 63,  67,  79,  77,  68],
       [ 98,  96,  71,  66,  94],
       [ 63,  98,  67,  74,  59],
       [ 77,  96,  61,  97,  98],
       [ 63,  63,  60,  75,  69],
       [ 50,  63,  98,  72,  52],
       [ 99,  76,  66,  62,  87],
       [ 71,  51,  87,  87,  90],
       [ 86,  81,  86,  58,  99],
       [ 97,  78,  75,  68,  87],
       [ 72,  60,  85,  73,  80],
       [ 75,  93,  68,  88,  56],
       [ 55,  73,  50,  72,  51],
       [ 80,  73,  88,  70,  90],
       [ 91,  81,  97,  57,  70],
       [ 84, 100,  71,  89,  76],
       [ 71,  50,  74,  55,  65],
       [ 79,  99,  80,  94,  75],
       [ 95,  65, 100,  66,  59],
       [ 61,  60,  61,  84,  80],
       [ 68,  58,  83,  53,  95],
       [ 97,  58,  87,  63,  82],
       [ 51,  61,  51,  56,  88],
       [ 62,  55,  98, 100,  55],
       [ 75,  

In [15]:
scores[0,:]
scores[:5,:]
scores[-5:,:]

array([[56, 72, 53, 66, 90],
       [84, 92, 55, 52, 53],
       [63, 64, 98, 53, 88],
       [75, 94, 61, 52, 97],
       [63, 72, 95, 88, 84]])

In [11]:
scores[:,0]

array([78, 78, 89, 50, 54, 63, 98, 63, 77, 63, 50, 99, 71, 86, 97, 72, 75,
       55, 80, 91, 84, 71, 79, 95, 61, 68, 97, 51, 62, 75, 55, 81, 88, 92,
       63, 92, 67, 87, 57, 93, 85, 98, 93, 72, 79, 56, 84, 63, 75, 63])

In [12]:
scores[:,1]

array([ 92,  73,  58,  83,  71,  67,  96,  98,  96,  63,  63,  76,  51,
        81,  78,  60,  93,  73,  73,  81, 100,  50,  99,  65,  60,  58,
        58,  61,  55,  77,  97,  94,  64,  70,  52,  84,  87,  78,  81,
        73,  53,  73,  69,  69,  63,  72,  92,  64,  94,  72])

In [14]:
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([419, 381, 356, 411, 338, 354, 425, 361, 429, 330, 335, 390, 386,
       410, 405, 370, 380, 301, 401, 396, 420, 315, 427, 385, 346, 357,
       387, 307, 370, 381, 353, 434, 358, 386, 342, 404, 355, 371, 401,
       398, 359, 441, 368, 350, 380, 337, 336, 366, 379, 402])

In [16]:
np.sum(scores,axis=1)

array([419, 381, 356, 411, 338, 354, 425, 361, 429, 330, 335, 390, 386,
       410, 405, 370, 380, 301, 401, 396, 420, 315, 427, 385, 346, 357,
       387, 307, 370, 381, 353, 434, 358, 386, 342, 404, 355, 371, 401,
       398, 359, 441, 368, 350, 380, 337, 336, 366, 379, 402])

In [17]:
np.mean(scores,axis=1)

array([83.8, 76.2, 71.2, 82.2, 67.6, 70.8, 85. , 72.2, 85.8, 66. , 67. ,
       78. , 77.2, 82. , 81. , 74. , 76. , 60.2, 80.2, 79.2, 84. , 63. ,
       85.4, 77. , 69.2, 71.4, 77.4, 61.4, 74. , 76.2, 70.6, 86.8, 71.6,
       77.2, 68.4, 80.8, 71. , 74.2, 80.2, 79.6, 71.8, 88.2, 73.6, 70. ,
       76. , 67.4, 67.2, 73.2, 75.8, 80.4])